[package]
name = "wasi-http"
authors = ["Credibil"]
categories = [
  "decentralized identity",
  "openid for verifiable data",
  "privacy",
  "security",
  "verifiable credentials",
]
edition = "2021"
homepage = "https://credibil.io"
keywords = ["credentials", "decentralized", "identity", "openid", "verifiable"]
readme = "README.md"
repository = "https://github.com/credibil-grid/wasi-http"
rust-version = "1.76"
version = "0.1.0-alpha.1"

[lib]
crate-type = ["cdylib", "lib"]

[lints.rust]
unused_extern_crates = "warn"
trivial_numeric_casts = "warn"
# unstable_features = "warn"
unused_import_braces = "warn"

[lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"

[dependencies]
anyhow = "1.0.86"
http = "1.1.0"
multipart = "0.18.0"
serde = "1.0.204"
serde_json = "1.0.120"
serde_urlencoded = "0.7.1"
tracing = "0.1.40"
wasi = "0.13.1"
url = "2.5.2"