[package]
authors.workspace = true
description = "Wrapper for wasi-http bindings"
edition.workspace = true
name = "wasi-http"
version = "0.1.0"

# [lib]
# crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
anyhow = "1.0.98"
http.workspace = true
serde = "1.0.219"
serde_json = "1.0.140"
serde_urlencoded = "0.7.1"
tracing = "0.1.41"
wasi = "0.14.2"
