[package]
name = "wasi-http"
description = "Wrapper for wasi-http bindings"
authors.workspace = true
edition.workspace = true
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
anyhow = "1.0.86"
http.workspace = true
serde = "1.0.204"
serde_json = "1.0.121"
serde_urlencoded = "0.7.1"
tracing = "0.1.40"
wasi = "0.13.1"
