[package]
authors.workspace = true
description = "Wrapper for wasi-http bindings"
edition.workspace = true
name = "wasi-http"
version = "0.1.0"

# [lib]
# crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
anyhow = "1.0.87"
http.workspace = true
serde = "1.0.210"
serde_json = "1.0.128"
serde_urlencoded = "0.7.1"
tracing = "0.1.40"
wasi = "0.13.2"
