[package]
authors = ["Credibil"]
categories = [
  "decentralized identity",
  "openid for verifiable data",
  "privacy",
  "security",
  "verifiable credentials",
]
edition = "2021"
homepage = "https://credibil.io"
keywords = ["credentials", "decentralized", "identity", "openid", "verifiable"]
name = "wasi-http"
readme = "README.md"
repository = "https://github.com/credibil-grid/wasi-http"
rust-version = "1.76"
version = "0.1.0-alpha.1"

# [lib]
# crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
anyhow = "1.0.86"
http.workspace = true
serde = "1.0.204"
serde_json = "1.0.121"
serde_urlencoded = "0.7.1"
tracing = "0.1.40"
wasi = "0.13.1"
