[package]
name = "sdk-otel"
description = "Wasm opentelemetry service"
authors.workspace = true
edition.workspace = true
version = "0.1.0"

[lints]
workspace = true

[features]
default = ["guest-mode"]
guest-mode = ["dep:async-trait", "dep:bytes", "dep:futures", "dep:http", "dep:opentelemetry-http", "dep:opentelemetry-otlp"]
host-mode = ["dep:num-traits"]

[dependencies]
anyhow.workspace = true
cfg-if = "1.0.3"
opentelemetry = "0.30.0"
opentelemetry_sdk = { version = "0.30.0", features = ["experimental_metrics_custom_reader"] }
sdk-http.workspace = true
tracing.workspace = true
tracing-opentelemetry = "0.31.0"
tracing-subscriber = { workspace = true, features = ["env-filter"] }
wit-bindgen = "0.44.0"

# host-mode dependencies
num-traits = { version = "0.2", optional = true }

# guest-mode dependencies
async-trait = { version = "0.1.89", optional = true }
bytes = { workspace = true, optional = true }
futures = { version = "0.3.31", optional = true }
http = { workspace = true, optional = true }
opentelemetry-http = { version = "0.30.0", default-features = false, optional = true }
opentelemetry-otlp = { version = "0.30.0", default-features = false, features = ["http-proto"], optional = true }
