[package]
name = "sdk-otel"
description = "Wasm opentelemetry service"
authors.workspace = true
edition.workspace = true
version = "0.1.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait = "0.1.89"
bytes.workspace = true
# futures = "0.3.31"
http.workspace = true
num-traits = "0.2"
opentelemetry = "0.30.0"
opentelemetry-http = { version = "0.30.0", default-features = false }
opentelemetry-otlp = { version = "0.30.0", default-features = false, features = ["http-proto"] }
opentelemetry_sdk = { version = "0.30.0", features = ["experimental_metrics_custom_reader"] }
sdk-http.workspace = true
tracing.workspace = true
tracing-opentelemetry = "0.31.0"
tracing-subscriber = { workspace = true, features = ["env-filter"] }
wasi.workspace = true
wit-bindgen = "0.44.0"
