[package]
name = "sdk-otel"
description = "Wasm opentelemetry service"
authors.workspace = true
edition.workspace = true
version = "0.1.0"

[lints]
workspace = true

[features]

[dependencies]
anyhow.workspace = true
wit-bindgen = "0.44.0"

async-trait = "0.1.88"
bytes.workspace = true
http.workspace = true
opentelemetry = "0.30.0"
opentelemetry-http = { version = "0.30.0", default-features = false }
opentelemetry-otlp = { version = "0.30.0", default-features = false, features = ["http-proto", "trace"] }
opentelemetry_sdk = "0.30.0"
sdk-http.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-opentelemetry = "0.31.0"
tracing-subscriber = { workspace = true, features = ["env-filter"] }
