[package]
name = "sdk-otel"
description = "Wasm opentelemetry service"
authors.workspace = true
edition.workspace = true
version = "0.1.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
num-traits = "0.2"
opentelemetry = "0.30.0"
opentelemetry_sdk = { version = "0.30.0", features = ["experimental_metrics_custom_reader"] }
tracing-opentelemetry = "0.31.0"
tracing-subscriber = { workspace = true, features = ["env-filter"] }
wasi.workspace = true
wit-bindgen = "0.44.0"
