
[package]
name = "wasmgrid"
description = "WASI Component runtime"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
default-run = "wasmgrid"
rust-version.workspace = true

[[bin]]
name = "wasmgrid"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-nats = "0.34.0"
async-trait.workspace = true
bytes.workspace = true
clap = { version = "4.5.4", features = ["derive"] }
futures.workspace = true
http-body-util = "0.1.1"
hyper = "1.3.1"
tokio = { version = "1.37.0", features=["signal"]}
tracing.workspace = true
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
wasi-keyvalue = { path = "crates/wasi-keyvalue" }
wasi-messaging = { path = "crates/wasi-messaging" }
wasmtime.workspace = true
wasmtime-wasi.workspace = true
wasmtime-wasi-http = "20.0.0"

[profile.release]
lto = true
opt-level = "s"
strip = true

[workspace]
members = [".", "crates/*", "examples/*"]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Credibil"]
rust-version = "1.77.2"

[workspace.lints.rust]
unused_extern_crates = "warn"
trivial_numeric_casts = "warn"
# unstable_features = "warn"
unused_import_braces = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"

[workspace.dependencies]
anyhow = "1.0.82"
async-trait = "0.1.80"
bytes = "1.6.0"
futures = "0.3.30"
tracing = "0.1.40"
wasmtime = { version = "20.0.0", default-features = false, features = ["runtime", "cranelift", "component-model"] }
wasmtime-wasi = "20.0.0"
