
[package]
name = "wasmgrid"
description = "WASI Component runtime"
default-run = "wasmgrid"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
version = "0.1.0"

[[bin]]
name = "wasmgrid"
path = "src/wasmgrid.rs"
doc = false

[lints]
workspace = true

[features]
default = ["compile"]
compile = ["runtime/compile"] # adds cranelift (+ ~4Mb)

[dependencies]
anyhow.workspace = true
dotenv = "0.15.0"
runtime.workspace = true
services = { path = "crates/services", features = ["blobstore", "http", "keyvalue"] }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[profile.release]
lto = true
opt-level = "s"
strip = true

[workspace]
members = ["crates/*", "examples/*"]
resolver = "3"

[workspace.package]
authors = ["Credibil"]
edition = "2024"
rust-version = "1.88"

[workspace.lints.rust]
trivial_numeric_casts = "warn"
unused_extern_crates = "warn"
# unstable_features = "warn"
unused_import_braces = "warn"

[workspace.lints.clippy]
all = "warn"
nursery = "warn"
pedantic = "warn"

[workspace.dependencies]
anyhow = "1.0.98"
azure_core = { version = "0.25.0", default-features = false, features = ["reqwest_rustls"] }
azure_identity = { version = "0.25.0", default-features = false }
azure_security_keyvault_secrets = { version = "0.4.0", default-features = false }
cfg-if = "1.0.1"
http = "1.3.1"
runtime = { path = "crates/runtime" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = "1.45.1"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }
wasi = "0.14.2"
wasi-bindings = { path = "crates/wasi-bindings" }
wasi-http-ext = { path = "crates/wasi-http-ext" }
wasmtime = { version = "33.0.0", default-features = false, features = ["component-model"] }
wasmtime-wasi = "33.0.0"
wasmtime-wasi-http-ext = "33.0.0"
wasmtime-wasi-io = "33.0.0"
