[workspace]
members = ["examples/guest"]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Credibil"]

[package]
name = "host"
description = "host for WASM guest for secure, isolated and distributed storage of wallet keys and credentials"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

# [[example]]
# name = "guest"
# path = "examples/guest"
# crate-type = ["cdylib"]
# targets = ["wasm32-wasi"]

[dependencies]
anyhow = "1.0.82"
async-nats = "0.34.0"
async-trait = "0.1.80"
bytes = "1.6.0"
clap = { version = "4.5.4", features = ["derive"] }
futures = "0.3.30"
log = "0.4.21"
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1.40"
wasmtime = { version = "19.0.2", features = ["component-model"] }
wasmtime-wasi = "19.0.2"
wit-bindgen-rt = "0.24.0"
wit-component = "0.203.0"

[package.metadata.component.target]
path = "wit"
world = "messaging"
