
[package]
name = "wasmgrid"
description = "WASI Component runtime"
default-run = "wasmgrid"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
version = "0.1.0"

[[bin]]
name = "wasmgrid"
path = "src/wasmgrid.rs"
doc = false

[[bin]]
name = "runtime"
path = "src/runtime.rs"
doc = false

[lints]
workspace = true

[features]
default = ["compile"]
compile = ["runtime/compile"] # adds cranelift (+ ~4Mb)

[dependencies]
anyhow.workspace = true
credibil-telemetry.workspace = true
dotenv = "0.15.0"
runtime.workspace = true
services = { path = "crates/services", features = ["blobstore", "http", "keyvalue"] }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[profile.release]
lto = true
opt-level = "s"
strip = true

[workspace]
members = ["crates/*", "examples/*"]
resolver = "3"

[workspace.package]
authors = ["Credibil"]
edition = "2024"
rust-version = "1.88"

[workspace.lints.rust]
trivial_numeric_casts = "warn"
unused_extern_crates = "warn"
# unstable_features = "warn"
unused_import_braces = "warn"

[workspace.lints.clippy]
all = "warn"
nursery = "warn"
pedantic = "warn"

[workspace.dependencies]
anyhow = "1.0.98"
axum = { version = "0.8.4", default-features = false }                                       # features = ["form", "json", "query", "tracing"]
azure_core = { version = "0.27.0", default-features = false, features = ["reqwest_rustls"] }
azure_identity = { version = "0.27.0", default-features = false }
azure_security_keyvault_secrets = { version = "0.6.0", default-features = false }
bytes = "1.10.1"
cfg-if = "1.0.1"
futures = "0.3.31"
http = "1.3.1"
http-client = { path = "crates/http-client" }
http-server = { path = "crates/http-server" }
resources = { path = "crates/resources", default-features = false }
runtime = { path = "crates/runtime" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
tokio = "1.47.1"
tower = "0.5.2"
tower-http = { version = "0.6.6", features = ["cors", "trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }
wasi = "0.14.2"
wasi-bindings = { path = "crates/wasi-bindings" }
wasmtime = { version = "35.0.0", default-features = false, features = ["component-model"] }
wasmtime-wasi = "35.0.0"
wasmtime-wasi-http = "35.0.0"
wasmtime-wasi-io = "35.0.0"

credibil-encoding = { git = "https://github.com/credibil/core.git" }
credibil-telemetry = { git = "https://github.com/credibil/core.git" }
