
[package]
authors.workspace = true
default-run = "wasmgrid"
description = "WASI Component runtime"
edition.workspace = true
name = "wasmgrid"
rust-version.workspace = true
version = "0.1.0"

[[bin]]
name = "wasmgrid"
path = "src/main.rs"

[lints]
workspace = true

[features]
default = ["http", "jsondb", "keyvalue", "rpc", "vault"]
http = ["dep:wasmtime-wasi-http"]
jsondb = ["dep:jmespath", "dep:mongodb"]
keyvalue = ["dep:async-nats"]
messaging = ["dep:async-nats"]
p2p = ["dep:iroh"]
rpc = ["dep:async-nats"]
vault = ["dep:azure_identity", "dep:azure_security_keyvault"]

[dependencies]
anyhow.workspace = true
async-nats = { version = "0.35.1", optional = true }
async-trait.workspace = true
azure_identity = { version = "0.20.0", optional = true, default-features = false, features = ["enable_reqwest_rustls"] }
azure_security_keyvault = { version = "0.20.0", optional = true, default-features = false }
base64ct = { version = "1.6.0", features = ["std"] }
bytes = "1.7.1"
clap = { version = "4.5.13", features = ["derive"] }
dotenv = "0.15.0"
futures = "0.3.30"
http = "1.1.0"
hyper = "1.4.1"
iroh = { version = "0.22.0", optional = true }
jmespath = { version = "0.3.0", optional = true }
mongodb = { version = "3.0.1", optional = true }
nkeys = "0.4.3"
serde_json.workspace = true
sha2 = "0.10.8"
tokio = { version = "1.39.2", features = ["signal"] }
tracing-subscriber.workspace = true
tracing.workspace = true
url = "2.5.2"
wasmtime-wasi-http = { workspace = true, optional = true }
wasmtime-wasi.workspace = true
wasmtime.workspace = true

[dev-dependencies]
ecdsa = "0.16.9"
k256 = "0.13.3"

[profile.release]
lto = true
opt-level = "s"
strip = true

[workspace]
members = [
  ".",
  "crates/*",
  "examples/http",
  "examples/http-http",
  "examples/http-msg",
  "examples/jsondb",
  "examples/keyvalue",
  "examples/messaging",
  "examples/p2p",
  "examples/rpc/client",
  "examples/rpc/server",
  "examples/vault",
]
resolver = "2"

[workspace.package]
authors = ["Credibil"]
edition = "2021"
rust-version = "1.77.2"

[workspace.lints.rust]
trivial_numeric_casts = "warn"
unused_extern_crates = "warn"
# unstable_features = "warn"
unused_import_braces = "warn"

[workspace.lints.clippy]
all = "warn"
nursery = "warn"
pedantic = "warn"

[workspace.dependencies]
anyhow = "1.0.86"
async-trait = "0.1.81"
http = "1.1.0"
serde = { version = "1.0.205", features = ["derive"] }
serde_json = "1.0.122"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
wasi = "0.13.1"
wasi-bindings = { path = "crates/wasi-bindings" }
wasi-http = { path = "crates/wasi-http" }
wasmtime = { version = "23.0.1", default-features = false, features = ["component-model", "cranelift", "runtime"] }
wasmtime-wasi = "23.0.1"
wasmtime-wasi-http = "23.0.1"
