
[package]
name = "wasmgrid"
description = "WASI Component runtime"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
default-run = "wasmgrid"
rust-version.workspace = true

[[bin]]
name = "wasmgrid"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-nats = "0.35.1"
async-trait.workspace = true
base64ct = { version = "1.6.0", features = ["std"] }
bson = { version = "2.10.0", features = ["chrono-0_4"] }
bytes = "1.6.0"
clap = { version = "4.5.4", features = ["derive"] }
dotenv = "0.15.0"
ecdsa = "0.16.9"
futures = "0.3.30"
http = "1.1.0"
http-body-util = "0.1.1"
hyper = "1.3.1"
iroh = "0.16.2"
jmespath = "0.3.0"
k256 = "0.13.3"
mongodb = "2.8.2"
regex = "1.10.4"
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = ["signal"] }
tracing.workspace = true
tracing-subscriber.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true
wasmtime-wasi-http.workspace = true

[profile.release]
lto = true
opt-level = "s"
strip = true

[workspace]
members = [
  ".",
  "crates/*",
  "examples/jsondb",
  "examples/http",
  "examples/http-http",
  "examples/http-msg",
  "examples/keyvault",
  "examples/messaging",
  "examples/p2p",
  "examples/wrpc/client",
  "examples/wrpc/server",
]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Credibil"]
rust-version = "1.77.2"

[workspace.lints.rust]
unused_extern_crates = "warn"
trivial_numeric_casts = "warn"
# unstable_features = "warn"
unused_import_braces = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"

[workspace.dependencies]
anyhow = "1.0.86"
async-trait = "0.1.80"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
wasi = "0.13.1"
wasi-bindings = { path = "crates/wasi-bindings" }
wasi-http = { path = "crates/wasi-http" }
wasmtime = { version = "21.0.1", default-features = false, features = ["component-model", "cranelift", "runtime"] }
wasmtime-wasi = "21.0.1"
wasmtime-wasi-http = "21.0.1"
