
[package]
name = "wasmgrid"
description = "WASI Component runtime"
default-run = "wasmgrid"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
version = "0.1.0"

# [lib]
# doctest = false

[[bin]]
name = "wasmgrid"
path = "src/wasmgrid.rs"
doc = false

[lints]
workspace = true

[features]
default = ["compile"]
compile = ["runtime/compile"]
# default = ["http", "jsondb", "keyvalue", "rpc", "vault"]

[dependencies]
anyhow.workspace = true
dotenv = "0.15.0"
runtime = { workspace = true }
services = { path = "crates/services", features = ["http", "jsondb", "keyvalue", "rpc", "vault"] }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[profile.release]
lto = true
opt-level = "s"
strip = true

[workspace]
members = [
  ".",
  "crates/*",
  "examples/http",
  "examples/http-http",
  "examples/http-msg",
  "examples/jsondb",
  "examples/keyvalue",
  "examples/messaging",
  # "examples/p2p",
  "examples/rpc/client",
  "examples/rpc/server",
  "examples/vault",
]
resolver = "3"

[workspace.package]
authors = ["Credibil"]
edition = "2024"
rust-version = "1.88"

[workspace.lints.rust]
trivial_numeric_casts = "warn"
unused_extern_crates = "warn"
# unstable_features = "warn"
unused_import_braces = "warn"

[workspace.lints.clippy]
all = "warn"
nursery = "warn"
pedantic = "warn"

[workspace.dependencies]
anyhow = "1.0.98"
http = "1.3.1"
mongodb = "3.2.3"
runtime = { path = "crates/runtime" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = "1.45.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }
wasi = "0.14.2"
wasi-bindings = { path = "crates/wasi-bindings" }
wasi-http = { path = "crates/wasi-http" }
wasmtime = { version = "32.0.0", default-features = false, features = ["component-model"] }
wasmtime-wasi = "32.0.0"
