global:
  scrape_interval: 15s

scrape_configs:
  # - job_name: "otel-collector"
  #   scrape_interval: 1s
  #   static_configs:
  #     - targets:
  #         - otelcol:8889

remote_write:
  - url: "http://localhost:9090/api/v1/write"
