[toolchain]
# channel = "stable"
channel = "nightly"
components = ["clippy", "rust-src", "rustfmt"]
targets = [
  "aarch64-apple-darwin",
  "wasm32-wasip1",
  # "wasm32-wasip2",
  "x86_64-unknown-linux-musl",
]
