[toolchain]
channel = "nightly"
components = ["clippy", "rust-src", "rustfmt"]
targets = [
  "aarch64-apple-darwin",
  "aarch64-unknown-linux-musl",
  "x86_64-unknown-linux-musl",
  "wasm32-wasip2",
]
# profile = "minimal" # "default"
