# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

max_width = 100
use_small_heuristics = "Max"

fn_params_layout = "Compressed"
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
reorder_impl_items = true
single_line_if_else_max_width = 50
single_line_let_else_max_width = 50
struct_lit_width = 20
unstable_features = true
use_field_init_shorthand = true
# wrap_comments = true
