[toolchain]
channel = "nightly"
# channel = "nightly-2024-07-28"
components = ["clippy", "rust-src", "rustfmt"]
targets = [
  "aarch64-apple-darwin",
  "x86_64-unknown-linux-musl",
  "aarch64-unknown-linux-musl",
  "wasm32-wasip1",
  # "wasm32-wasip2",
]
# profile = "minimal" # "default"
