[package]
name = "jsondb"
edition.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
http = "1.1.0"
serde_json = "1.0.117"
tracing.workspace = true
tracing-subscriber.workspace = true
openid4vc = { git = "https://github.com/vercre/vercre" }
wasi.workspace = true
wasi-bindings.workspace = true
wasi-http.workspace = true
