[package]
authors.workspace = true
edition.workspace = true
name = "jsondb"

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
http.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
vercre-openid = { git = "https://github.com/vercre/vercre" }
wasi.workspace = true
wasi-bindings.workspace = true
wasi-http.workspace = true
