[package]
name = "jsondb"
edition.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
http.workspace = true
openid4vc = { git = "https://github.com/vercre/vercre" }
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wasi.workspace = true
wasi-bindings.workspace = true
wasi-http.workspace = true
