[package]
authors.workspace = true
description = "Wasm services"
edition.workspace = true
name = "services"
version = "0.1.0"

# [lib]
# crate-type = ["cdylib"]

[lints]
workspace = true

[features]
default = ["http", "keyvault-azure"]
http = ["dep:wasmtime-wasi-http"]
jsondb-mongodb = ["dep:jmespath", "dep:mongodb", "resources/mongodb"]
kv-nats = ["dep:async-nats", "resources/nats"]
msg-nats = ["dep:async-nats", "resources/nats"]
rpc-nats = ["dep:async-nats"]
keyvault-azure = ["dep:azure_core", "dep:azure_security_keyvault_keys", "dep:openssl", "resources/azkeyvault"]

[dependencies]
anyhow.workspace = true
async-nats = { version = "0.41.0", optional = true }
async-trait = "0.1.88"
azure_core = { version = "0.24.0", optional = true, default-features = false, features = ["reqwest_rustls"] }
azure_security_keyvault_keys = { version = "0.3.0", optional = true, default-features = false }
base64ct = { version = "1.7.3", features = ["std"] }
bytes = "1.10.1"
futures = "0.3.31"
http.workspace = true
hyper = "1.6.0"
jmespath = { version = "0.3.0", optional = true }
mongodb = { version = "3.2.3", optional = true }
resources = { path = "../resources", default-features = false }
runtime.workspace = true
serde_json.workspace = true
sha2 = "0.10.9"
tokio = { workspace = true, features = ["macros", "signal"] }
tracing.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true
wasmtime-wasi-http = { version = "32.0.0", optional = true }

# required for azure_identity, etc.
openssl = { version = "0.10", optional = true, features = ["vendored"] }

[dev-dependencies]
async-nats = "0.41.0"
ecdsa = "0.16.9"
k256 = "0.13.4"
