[package]
name = "services"
description = "Wasm services"
authors.workspace = true
edition.workspace = true
version = "0.1.0"

# [lib]
# crate-type = ["cdylib"]

[lints]
workspace = true

[features]
default = ["http"]
http = ["dep:wasmtime-wasi-http"]
jsondb = ["dep:jmespath", "dep:mongodb"]
keyvalue = ["dep:async-nats"]
messaging = ["dep:async-nats"]
p2p = ["dep:iroh"]
rpc = ["dep:async-nats"]
vault = ["dep:azure_identity", "dep:azure_security_keyvault"]

[dependencies]
anyhow.workspace = true
async-nats = { version = "0.40.0", optional = true }
async-trait = "0.1.88"
azure_identity = { version = "0.23.0", optional = true, default-features = false }
azure_security_keyvault = { version = "0.21.0", optional = true, default-features = false }
bytes = "1.10.1"
futures = "0.3.31"
http.workspace = true
hyper = "1.6.0"
iroh = { version = "0.29.0", optional = true }
jmespath = { version = "0.3.0", optional = true }
mongodb = { workspace = true, optional = true }
nkeys = "0.4.4"
runtime.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["macros", "signal"] }
tracing.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true
wasmtime-wasi-http = { version = "32.0.0", optional = true }

# ecdsa = "0.16.9"
# k256 = "0.13.4"
