[package]
name = "wasi-bindings"
description = "Guest bindings for wasmgrid service"
authors.workspace = true
edition.workspace = true
version = "0.1.0"

# [lib]
# crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
wit-bindgen = "0.42.1"
