[package]
authors.workspace = true
description = "Guest bindings for wasmgrid capabilities"
edition.workspace = true
name = "wasi-bindings"
version = "0.1.0"

# [lib]
# crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
wit-bindgen = "0.28.0"
