[package]
name = "wasi-bindings"
description = "WASM guest bindings for wasmgrid capabilities"
authors.workspace = true
edition.workspace = true
version = "0.1.0"

# [lib]
# crate-type = ["lib"]

[lints]
workspace = true

[dependencies]
wit-bindgen = "0.28.0"
