[package]
authors.workspace = true
description = "Guest bindings for wasmgrid service"
edition.workspace = true
name = "wasi-bindings"
version = "0.1.0"

# [lib]
# crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
serde.workspace = true
wit-bindgen = "0.42.1"
