[package]
name = "http-msg"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
http = "1.1.0"
serde_json = "1.0.117"
tracing-subscriber.workspace = true
tracing.workspace = true
wasi-bindings.workspace = true
wasi-http.workspace = true
wasi.workspace = true
