[package]
name = "messaging"
description = "WASM guest for secure, isolated and distributed storage of wallet keys and credentials"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
# bitflags = "2.5.0"
wit-bindgen-rt = "0.24.0"

[package.metadata.component]
package = "component:messaging"

[package.metadata.component.target]
# path = "wit"
# world = "messaging"

[package.metadata.component.target.dependencies]
"wasi:messaging" = { path = "../../crates/wasi-messaging/wit" }
