[package]
name = "messaging-guest"
description = "WASM guest for secure, isolated and distributed storage of wallet keys and credentials"
version = "0.1.0"

authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
# bitflags = "2.5.0"
wit-bindgen-rt = "0.24.0"

[package.metadata.component]
package = "wasi:messaging"

[package.metadata.component.target]
path = "../../crates/wasi-messaging/wit"
world = "messaging"

[package.metadata.component.dependencies]
