[package]
name = "messaging"
edition.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true
wasi-bindings.workspace = true

# [package.metadata.component]
# package = "component:messaging"

# [package.metadata.component.target]
# world = "messaging"
# # path = "wit"

# [package.metadata.component.target.dependencies]
# "wasi:messaging" = { path = "wit/deps/messaging" }
# wit-bindgen-rt = "0.24.0"
