package wasmgrid:service;

world blobstore {
	include wasi:blobstore/imports@0.2.0-draft;
}

world keyvalue {
	include wasi:keyvalue/watch-service@0.2.0-draft2;
}

world messaging {
	include wasi:messaging/messaging-request-reply@0.2.0-draft;
}

world otel {
	include wasi:otel/imports@0.2.0-draft;
}

world sql {
	include wasi:sql/imports@0.2.0-draft;
}

world vault {
	include wasi:vault/imports@0.1.0-draft;
}