package wasmgrid:service;

world jsondb {
	include wasi:jsondb/imports@0.1.0-draft;
}

world keyvalue {
	include wasi:keyvalue/imports@0.2.0-draft;
	export wasi:keyvalue/watcher@0.2.0-draft;
}

world messaging {
	include wasi:messaging/imports@0.2.0-draft;
	export wasi:messaging/messaging-guest@0.2.0-draft;
}

world vault {
	include wasi:vault/imports@0.1.0-draft;
}

// world p2p {
// 	include wasi:p2p/imports@0.1.0-draft;
// }

world rpc {
	include wasi:rpc/imports@0.1.0-draft;
	export wasi:rpc/server@0.1.0-draft;
}