# https://doc.rust-lang.org/cargo/reference/config.html

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"

[target.wasm32-wasip1]
rustflags = ["-C", "target-cpu=mvp"]

# [unstable]
# build-std = ["panic_abort", "std"]
