[package]
authors.workspace = true
edition.workspace = true
name = "rpc-server"

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wasi-bindings.workspace = true
