[package]
name = "rpc-server"
edition.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wasi-bindings.workspace = true
