[package]
name = "keyvault"
edition.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
http = "1.1.0"
serde_json = "1.0.120"
tracing.workspace = true
tracing-subscriber.workspace = true
wasi.workspace = true
wasi-bindings.workspace = true
wasi-http.workspace = true
