[package]
name = "keyvault"
description = "WASM guest for secure, isolated and distributed storage of wallet keys and credentials"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
http = "1.1.0"
serde_json = "1.0.117"
tracing-subscriber.workspace = true
tracing.workspace = true
wasex.workspace = true
wasi-bindings.workspace = true
wasi.workspace = true
