[package]
name = "http"
version = "0.1.0"
edition = "2021"
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
http = "1.1.0"
http-shared.workspace = true
serde_json = "1.0.117"
tracing.workspace = true
tracing-subscriber.workspace = true
wasi.workspace = true
