[package]
name = "blobstore"
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wasi.workspace = true
wasi-bindings.workspace = true
wasi-http-ext.workspace = true
