[package]
name = "p2p"
description = "WASM guest for demonstrating storage of a message on a Peer-to-Peer network node"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
http = "1.1.0"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
tracing-subscriber.workspace = true
tracing.workspace = true
wasi-bindings.workspace = true
wasi-http.workspace = true
wasi.workspace = true
