[package]
name = "docdb"
description = "WASM guest example executing SQL queries"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bson = "2.10.0"
http = "1.1.0"
serde_json = "1.0.117"
tracing.workspace = true
tracing-subscriber.workspace = true
vercre-core = { git = "https://github.com/vercre/vercre" }
wasex.workspace = true
wasi.workspace = true
wasi-bindings.workspace = true
