[package]
name = "vault"
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
base64ct = { version = "1.7.3", features = ["std"] }
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wasi.workspace = true
wasi-bindings.workspace = true
wasi-http.workspace = true
