[package]
name = "http-sql"
description = "WASM guest example executing SQL queries"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
http = "1.1.0"
serde_json = "1.0.116"
vercre-core = { git = "https://github.com/vercre/vercre" }
wasi = "0.13.0"
wasi-bindings = { path = "../../crates/wasi-bindings" }
