[package]
name = "wrpc-client"
version = "0.1.0"
# workspace = "../../.."
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
http = "1.1.0"
serde.workspace = true
serde_json.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
wasex.workspace = true
wasi-bindings.workspace = true
wasi.workspace = true
