# Builds a Docker image and publishes to the Azure Container Registry

name: Deploy

on:
  push:
    branches: [main]
    paths:
      - 'Cargo.lock'
      - 'src/**'
      - crates/**
  pull_request:
    branches: [main]
    paths:
      - 'Cargo.lock'
      - 'src/**'
      - crates/**

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: acrcredibil.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            acrcredibil.azurecr.io/demo/${{ github.event.repository.name }}:latest
