# Builds a Docker image and publishes to the Azure Container Registry

name: Deploy

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # -----------------------------------------------------------------------
  # Determine if anything interesting has changed
  # -----------------------------------------------------------------------
  changes:
    name: Detect changes
    if: |
      ${{ github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name !=
      github.event.pull_request.base.repo.full_name }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      wasmgrid: ${{ steps.changes.outputs.wasmgrid }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            wasmgrid:
              - 'src/**'

  # -----------------------------------------------------------------------
  # Deploy Container App
  # -----------------------------------------------------------------------
  publish:
    name: Publish
    needs: changes
    if: ${{ needs.changes.outputs.wasmgrid == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # id-token: write
      # packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: acrcredibil.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
